# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d316676e46bfd7868dd10c83b7095d39593146076d783ad91124f011fb85515646f1b271422df9f670dd5281c197b5b385c30bccdada66d04cdd5fb61f1eb8f6

test:
  secret_key_base: 17fa76fca6e908a04930444905a716475421a6e6d7773cddacec68519c20aa5e2c17d726c428c2a37983ae0e5c73b49e15e2c64419dfb3520d41e99b109a820c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
